# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab779fb44b04388559912f92387a19ca31c13c4787b88e84f98cd4df7cbdecf401341b21e3ddc93d61b696f5e6583439713e1b78b7357ca3634dee1be46330b7

test:
  secret_key_base: f06709ff166c70ab77e6c5a963fe7baa16047b13201bf913e085d3952742dc8b56391b87928e540e0e4ad85ccee5267667dbc070011ced64f27461eda3349849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
